language: php

env:
    global:
    - secure: "EFiiOhppAWDnoGjIHOkTY08F5EF87uPlqBLY9UfNSLA83JBsqYOPTxIfk8Y1cmNctK2x5bwl6/VFB65qkYBw0zwr3iQsqxjaJ/EfoX3yDIyrPOd+dqXcJQWkYhjs3UjslCS0yrUCTgfrzkaHNoFspFMbC1n73//vhaNtIyDAMm0="

php:
  - 5.5

before_script:
    - composer install
    - git clone https://github.com/encorephp/kernel
    - composer install -d kernel
    - curl -O https://download.sculpin.io/sculpin.phar

script: 
    - php ./sculpin.phar generate --env=prod
    - php bin/sami.php update api.php

after_success:
    - sh ./deploy.sh
