language: php

env:
    global:
    - secure: "EFiiOhppAWDnoGjIHOkTY08F5EF87uPlqBLY9UfNSLA83JBsqYOPTxIfk8Y1cmNctK2x5bwl6/VFB65qkYBw0zwr3iQsqxjaJ/EfoX3yDIyrPOd+dqXcJQWkYhjs3UjslCS0yrUCTgfrzkaHNoFspFMbC1n73//vhaNtIyDAMm0="

php:
  - 5.6

before_script:
    - travis_retry curl -O https://download.sculpin.io/sculpin.phar
    - travis_retry php sculpin.phar install --project-dir=site
    - travis_retry composer install -d site

script: 
    - php sculpin.phar generate --project-dir=site --env=prod
    - php site/vendor/bin/sami.php update api.php

after_success:
    - travis_retry bin/deploy
