var tree = [["Encore",,"",
                [["Compiler","Encore\/Compiler.html","",
                [["Command","Encore\/Compiler\/Command.html"," < Command",
                [        ]],["ServiceProvider","Encore\/Compiler\/ServiceProvider.html"," < ServiceProvider",
                [        ]]        ]],["Composer","Encore\/Composer.html","",
                [["Script","Encore\/Composer\/Script.html","",
                [        ]]        ]],["Config","Encore\/Config.html","",
                [["FileLoader","Encore\/Config\/FileLoader.html","",
                [        ]],["LoaderInterface","Encore\/Config\/LoaderInterface.html","",
                [        ]],["Proxy","Encore\/Config\/Proxy.html"," < Proxy",
                [        ]],["Repository","Encore\/Config\/Repository.html","",
                [        ]],["ServiceProvider","Encore\/Config\/ServiceProvider.html"," < ServiceProvider",
                [        ]]        ]],["Console","Encore\/Console.html","",
                [["Error","Encore\/Console\/Error.html","",
                [["ConsoleDisplayer","Encore\/Console\/Error\/ConsoleDisplayer.html","",
                [        ]]        ]],["Application","Encore\/Console\/Application.html"," < Application",
                [        ]],["Command","Encore\/Console\/Command.html"," < Command",
                [        ]],["Proxy","Encore\/Console\/Proxy.html"," < Proxy",
                [        ]],["ServiceProvider","Encore\/Console\/ServiceProvider.html"," < ServiceProvider",
                [        ]]        ]],["Container","Encore\/Container.html","",
                [["Container","Encore\/Container\/Container.html","",
                [        ]],["ContainerAwareInterface","Encore\/Container\/ContainerAwareInterface.html","",
                [        ]],["ContainerAwareTrait","Encore\/Container\/ContainerAwareTrait.html","",
                [        ]],["Definition","Encore\/Container\/Definition.html","",
                [        ]],["EventDispatcherInterface","Encore\/Container\/EventDispatcherInterface.html","",
                [        ]],["Proxy","Encore\/Container\/Proxy.html","",
                [        ]],["ServiceProvider","Encore\/Container\/ServiceProvider.html","",
                [        ]]        ]],["Controller","Encore\/Controller.html","",
                [["Controller","Encore\/Controller\/Controller.html","",
                [        ]],["ControllerAwareInterface","Encore\/Controller\/ControllerAwareInterface.html","",
                [        ]],["ControllerAwareTrait","Encore\/Controller\/ControllerAwareTrait.html","",
                [        ]],["ServiceProvider","Encore\/Controller\/ServiceProvider.html"," < ServiceProvider",
                [        ]]        ]],["Database",,"",
                [["Command","Encore\/Database\/Command.html","",
                [["GenerateMigration","Encore\/Database\/Command\/GenerateMigration.html"," < Command",
                [        ]],["GenerateModel","Encore\/Database\/Command\/GenerateModel.html"," < Command",
                [        ]],["MigrationDown","Encore\/Database\/Command\/MigrationDown.html"," < Command",
                [        ]],["MigrationMigrate","Encore\/Database\/Command\/MigrationMigrate.html"," < Command",
                [        ]],["MigrationStatus","Encore\/Database\/Command\/MigrationStatus.html"," < Command",
                [        ]],["MigrationUp","Encore\/Database\/Command\/MigrationUp.html"," < Command",
                [        ]]        ]]        ]],["Development","Encore\/Development.html","",
                [["Command","Encore\/Development\/Command.html","",
                [["Debug","Encore\/Development\/Command\/Debug.html"," < Command",
                [        ]]        ]],["Task",,"",
                [["Composer","Encore\/Development\/Task\/Composer.html","",
                [["loadTasks","Encore\/Development\/Task\/Composer\/loadTasks.html","",
                [        ]]        ]]        ]],["ServiceProvider","Encore\/Development\/ServiceProvider.html"," < ServiceProvider",
                [        ]],["TaskInfo","Encore\/Development\/TaskInfo.html"," < TaskInfo",
                [        ]],["Tasks","Encore\/Development\/Tasks.html"," < Tasks",
                [        ]]        ]],["Error","Encore\/Error.html","",
                [["Displayer","Encore\/Error\/Displayer.html","",
                [["BasicDisplayer","Encore\/Error\/Displayer\/BasicDisplayer.html","",
                [        ]],["DisplayerInterface","Encore\/Error\/Displayer\/DisplayerInterface.html","",
                [        ]]        ]],["ExceptionHandler","Encore\/Error\/ExceptionHandler.html"," < ExceptionHandler",
                [        ]],["Handler","Encore\/Error\/Handler.html","",
                [        ]],["Proxy","Encore\/Error\/Proxy.html"," < Proxy",
                [        ]],["ServiceProvider","Encore\/Error\/ServiceProvider.html"," < ServiceProvider",
                [        ]]        ]],["Events","Encore\/Events.html","",
                [["ContainerDispatcher","Encore\/Events\/ContainerDispatcher.html","",
                [        ]],["Dispatcher","Encore\/Events\/Dispatcher.html","",
                [        ]],["DispatcherInterface","Encore\/Events\/DispatcherInterface.html","",
                [        ]],["Proxy","Encore\/Events\/Proxy.html"," < Proxy",
                [        ]],["ServiceProvider","Encore\/Events\/ServiceProvider.html"," < ServiceProvider",
                [        ]]        ]],["Filesystem","Encore\/Filesystem.html","",
                [["FileNotFoundException","Encore\/Filesystem\/FileNotFoundException.html"," < Exception",
                [        ]],["Filesystem","Encore\/Filesystem\/Filesystem.html","",
                [        ]],["Proxy","Encore\/Filesystem\/Proxy.html"," < Proxy",
                [        ]],["ServiceProvider","Encore\/Filesystem\/ServiceProvider.html"," < ServiceProvider",
                [        ]]        ]],["Giml","Encore\/Giml.html","",
                [["Exception","Encore\/Giml\/Exception.html","",
                [["DuplicateIdException","Encore\/Giml\/Exception\/DuplicateIdException.html"," < Exception",
                [        ]],["InvalidElementException","Encore\/Giml\/Exception\/InvalidElementException.html"," < Exception",
                [        ]]        ]],["Reservation","Encore\/Giml\/Reservation.html","",
                [["RequireReservation","Encore\/Giml\/Reservation\/RequireReservation.html","",
                [        ]],["ReservationInterface","Encore\/Giml\/Reservation\/ReservationInterface.html","",
                [        ]],["ReservationTrait","Encore\/Giml\/Reservation\/ReservationTrait.html","",
                [        ]]        ]],["CollectionInterface","Encore\/Giml\/CollectionInterface.html","",
                [        ]],["ElementCollection","Encore\/Giml\/ElementCollection.html","",
                [        ]],["ElementFactoryInterface","Encore\/Giml\/ElementFactoryInterface.html","",
                [        ]],["ElementInterface","Encore\/Giml\/ElementInterface.html","",
                [        ]],["ElementTrait","Encore\/Giml\/ElementTrait.html","",
                [        ]],["NamespaceElementFactory","Encore\/Giml\/NamespaceElementFactory.html","",
                [        ]],["Parser","Encore\/Giml\/Parser.html","",
                [        ]],["Reader","Encore\/Giml\/Reader.html"," < Reader",
                [        ]],["ReaderInterface","Encore\/Giml\/ReaderInterface.html","",
                [        ]],["ServiceProvider","Encore\/Giml\/ServiceProvider.html"," < ServiceProvider",
                [        ]]        ]],["Kernel","Encore\/Kernel.html","",
                [["Proxy","Encore\/Kernel\/Proxy.html","",
                [["App","Encore\/Kernel\/Proxy\/App.html"," < Proxy",
                [        ]]        ]],["AliasLoader","Encore\/Kernel\/AliasLoader.html","",
                [        ]],["Application","Encore\/Kernel\/Application.html"," < Container",
                [        ]],["Timezone","Encore\/Kernel\/Timezone.html","",
                [        ]]        ]],["Namespacer","Encore\/Namespacer.html","",
                [["Namespacable","Encore\/Namespacer\/Namespacable.html"," < Resolver",
                [        ]],["NamespacableInterface","Encore\/Namespacer\/NamespacableInterface.html","",
                [        ]],["NamespacableTrait","Encore\/Namespacer\/NamespacableTrait.html","",
                [        ]],["Resolver","Encore\/Namespacer\/Resolver.html","",
                [        ]],["ResolverInterface","Encore\/Namespacer\/ResolverInterface.html","",
                [        ]]        ]],["Repl","Encore\/Repl.html","",
                [["Command","Encore\/Repl\/Command.html"," < Command",
                [        ]],["ServiceProvider","Encore\/Repl\/ServiceProvider.html"," < ServiceProvider",
                [        ]],["ShallowParser","Encore\/Repl\/ShallowParser.html","",
                [        ]]        ]],["Resource","Encore\/Resource.html","",
                [["Command","Encore\/Resource\/Command.html","",
                [["Publish","Encore\/Resource\/Command\/Publish.html"," < Command",
                [        ]]        ]],["FileFinder","Encore\/Resource\/FileFinder.html","",
                [        ]],["FinderInterface","Encore\/Resource\/FinderInterface.html","",
                [        ]],["FinderTrait","Encore\/Resource\/FinderTrait.html","",
                [        ]],["ServiceProvider","Encore\/Resource\/ServiceProvider.html"," < ServiceProvider",
                [        ]]        ]],["Testing","Encore\/Testing.html","",
                [["Command","Encore\/Testing\/Command.html"," < Command",
                [        ]],["ServiceProvider","Encore\/Testing\/ServiceProvider.html"," < ServiceProvider",
                [        ]]        ]],["View","Encore\/View.html","",
                [["Parser",,"",
                [["Style","Encore\/View\/Parser\/Style.html","",
                [["ParserInterface","Encore\/View\/Parser\/Style\/ParserInterface.html","",
                [        ]],["Yaml","Encore\/View\/Parser\/Style\/Yaml.html","",
                [        ]]        ]],["View","Encore\/View\/Parser\/View.html","",
                [["Giml","Encore\/View\/Parser\/View\/Giml.html"," < Parser",
                [        ]],["ParserInterface","Encore\/View\/Parser\/View\/ParserInterface.html","",
                [        ]]        ]]        ]],["Style","Encore\/View\/Style.html","",
                [["StyleAwareInterface","Encore\/View\/Style\/StyleAwareInterface.html","",
                [        ]],["StyleCollection","Encore\/View\/Style\/StyleCollection.html","",
                [        ]]        ]],["Manager","Encore\/View\/Manager.html","",
                [        ]],["Proxy","Encore\/View\/Proxy.html"," < Proxy",
                [        ]],["ServiceProvider","Encore\/View\/ServiceProvider.html"," < ServiceProvider",
                [        ]],["View","Encore\/View\/View.html","",
                [        ]]        ]],["Wx","Encore\/Wx.html","",
                [["Command","Encore\/Wx\/Command.html","",
                [["Install","Encore\/Wx\/Command\/Install.html"," < Command",
                [        ]]        ]],["Element","Encore\/Wx\/Element.html","",
                [["Raw","Encore\/Wx\/Element\/Raw.html","",
                [["TaskBarIcon","Encore\/Wx\/Element\/Raw\/TaskBarIcon.html"," < wxTaskBarIcon",
                [        ]]        ]],["Traits","Encore\/Wx\/Element\/Traits.html","",
                [["Events","Encore\/Wx\/Element\/Traits\/Events.html","",
                [        ]],["Options","Encore\/Wx\/Element\/Traits\/Options.html","",
                [        ]],["Positionable","Encore\/Wx\/Element\/Traits\/Positionable.html","",
                [        ]],["Sizable","Encore\/Wx\/Element\/Traits\/Sizable.html","",
                [        ]],["Wx","Encore\/Wx\/Element\/Traits\/Wx.html","",
                [        ]]        ]],["BoxSizer","Encore\/Wx\/Element\/BoxSizer.html","",
                [        ]],["Button","Encore\/Wx\/Element\/Button.html","",
                [        ]],["CheckBox","Encore\/Wx\/Element\/CheckBox.html","",
                [        ]],["DatePicker","Encore\/Wx\/Element\/DatePicker.html","",
                [        ]],["Frame","Encore\/Wx\/Element\/Frame.html","",
                [        ]],["Label","Encore\/Wx\/Element\/Label.html","",
                [        ]],["Menu","Encore\/Wx\/Element\/Menu.html","",
                [        ]],["MenuBar","Encore\/Wx\/Element\/MenuBar.html","",
                [        ]],["MenuItem","Encore\/Wx\/Element\/MenuItem.html","",
                [        ]],["Panel","Encore\/Wx\/Element\/Panel.html","",
                [        ]],["RadioButton","Encore\/Wx\/Element\/RadioButton.html","",
                [        ]],["TaskBarIcon","Encore\/Wx\/Element\/TaskBarIcon.html","",
                [        ]],["TextBox","Encore\/Wx\/Element\/TextBox.html","",
                [        ]],["WebView","Encore\/Wx\/Element\/WebView.html","",
                [        ]]        ]],["ClosureCallback","Encore\/Wx\/ClosureCallback.html","",
                [        ]],["Collection","Encore\/Wx\/Collection.html","",
                [        ]],["ServiceProvider","Encore\/Wx\/ServiceProvider.html"," < ServiceProvider",
                [        ]],["Widgets","Encore\/Wx\/Widgets.html"," < wxApp",
                [        ]]        ]]        ]]        ]

